### ISSUE TITLE
Add to Variables reading a short discussion of code commenting

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/mobile-development-with-ios-track#6]
Add an objective about recognizing line comments (//) and block block comments (/\* */)

**Comment by AnnJohn** [comment]
Also @markedwardmurray does this PR request also address https://github.com/learn-co-curriculum/reading-ios-variables-and-data-types/issues/5 

(you mentioned that it could be a solution for it)

**Comment by markedwardmurray** [comment]
sufficiently, i think.

**Comment by AnnJohn** [comment]
@markedwardmurray  that works, so we can just close that issue too when the PR is merged. thanks

**Comment by markedwardmurray** [comment]
yeah i close relevant issues on the repos when i deploy revisions.

**Comment by AnnJohn** [comment]
:+1:

**Comment by markedwardmurray** [comment]
resolved by https://github.com/learn-co-curriculum/reading-ios-variables-and-data-types/pull/6
